Packets DEFINITIONS EXPLICIT TAGS ::= BEGIN

Standard ::= SEQUENCE {
	payload OCTET STRING
}

File ::= SEQUENCE {
	filePath OCTET STRING,
	start INTEGER,
	end INTEGER,
	payload OCTET STRING
}

Viewport ::= SEQUENCE {
	xStart INTEGER,
	xEnd INTEGER,
	yStart INTEGER,
	yEnd INTEGER,
	payload OCTET STRING
}

Packet ::= SEQUENCE {
	id INTEGER,
	payload CHOICE {
		standard [0] Standard,
		file [1] File,
		viewport [2] Viewport
	}
} 

END
