/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Packets"
 * 	found in "packets.asn1"
 */

#ifndef	_Packet_H_
#define	_Packet_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <UTF8String.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Packet */
typedef struct Packet {
	long	 method;
	UTF8String_t	 payload;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Packet_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Packet;

#ifdef __cplusplus
}
#endif

#endif	/* _Packet_H_ */
#include <asn_internal.h>
